apiVersion: v1
kind: Template
metadata:
  name: launchpad-builder
  annotations:
    description: This template creates a Build Configuration using an S2I builder.
    tags: instant-app
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wfswarm-rest-http-secured
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wfswarm-rest-http-secured
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: wfswarm-rest-http-secured:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/wfswarm-rest-http-secured-parent/wfswarm-rest-http-secured
      prometheus.io/port: "9779"
      fabric8.io/scm-url: https://github.com/openshiftio/wfswarm-rest-http-secured-parent/wfswarm-rest-http-secured
      fabric8.io/iconUrl: img/icons/wildfly.svg
      fabric8.io/git-branch: sso_s2i
      prometheus.io/scrape: "true"
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/wfswarm-rest-http-secured-parent/wfswarm-rest-http-secured
      fabric8.io/scm-tag: booster-parent-10
    labels:
      expose: "true"
      app: wfswarm-rest-http-secured
      provider: fabric8
      version: 5-SNAPSHOT
      group: io.openshift.booster
    name: wfswarm-rest-http-secured
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wfswarm-rest-http-secured
      provider: fabric8
      group: io.openshift.booster
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: wfswarm-rest-http-secured
      provider: fabric8
      version: 5-SNAPSHOT
      group: io.openshift.booster
    name: wfswarm-rest-http-secured
  spec:
    replicas: 1
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: wfswarm-rest-http-secured
          provider: fabric8
          version: 5-SNAPSHOT
          group: io.openshift.booster
      spec:
        containers:
        - env:
          - name: JAVA_APP_DIR
            value: /deployments
          - name: SSO_AUTH_SERVER_URL
            value: ${SSO_AUTH_SERVER_URL}
          - name: JAVA_OPTIONS
            value: -Dsso.auth.server.url=${SSO_AUTH_SERVER_URL}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: wfswarm-rest-http-secured:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: wfswarm-rest-http-secured
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wfswarm-rest-http-secured
        from:
          kind: ImageStreamTag
          name: wfswarm-rest-http-secured:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: wfswarm-rest-http-secured
      provider: fabric8
      version: 5-SNAPSHOT
      group: io.openshift.booster
    name: wfswarm-rest-http-secured
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: wfswarm-rest-http-secured
